plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'java-library'
    id 'maven-publish'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

loom {
    accessWidenerPath = file('src/main/resources/keybindbundles.accesswidener')
}

repositories {
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
    maven { url 'https://maven.blamejared.com/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    modCompileOnly("com.blamejared.controlling:Controlling-fabric-${minecraft_version}:${controlling_version}")
}

def expandedResourceProperties = [
        version          : version.toString(),
        minecraft_version: minecraft_version,
        loader_version   : loader_version
]

processResources {
    inputs.properties expandedResourceProperties

    filesMatching('fabric.mod.json') {
        expand expandedResourceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

jar {
    def archiveName = base.archivesName.get()
    from('LICENSE') {
        rename { "${it}_${archiveName}" }
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}
