# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=1.21.1
loader_version=0.19.3
loom_version=1.17.19
fabric_api_version=0.116.15+1.21.1
controlling_version=19.0.5

# Mod Properties
mod_id=keybindbundles
mod_name=KeyBind Bundles
mod_license=MIT
mod_version=1.4.0
mod_group_id=com.matyrobbrt.keybindbundles
mod_authors=Matyrobbrt, ashleywr (Fabric port)
mod_description=Unofficial Fabric port of KeyBind Bundles. Bundle keybinds into radial menus.
